In [50]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [15]:
import os
path = os.getcwd() + '/auto-mpg.csv'
raw_data = pd.read_csv(path)
raw_data.head()

    mpg  displacement
0  18.0         307.0
1  15.0         350.0
2  18.0         318.0
3  16.0         304.0
4  17.0         302.0

In [16]:
raw_data.describe()

              mpg  displacement
count  398.000000    398.000000
mean    23.514573    193.425879
std      7.815984    104.269838
min      9.000000     68.000000
25%     17.500000    104.250000
50%     23.000000    148.500000
75%     29.000000    262.000000
max     46.600000    455.000000

In [51]:
data = ( raw_data - raw_data.mean() )/( raw_data.max()-raw_data.min())
data.head()

        mpg  displacement
0 -0.146664      0.293473
1 -0.226451      0.404584
2 -0.146664      0.321897
3 -0.199856      0.285721
4 -0.173260      0.280553

In [52]:
data.shape

(398, 2)

In [53]:
cols = data.shape[1]
print(cols)

2

In [ ]:
data.insert(cols,'Ones',1)
data.head()

In [57]:
cols = data.shape[1]
print(cols)

3

In [69]:
x = data.iloc[:,1:cols]
y = data.iloc[:,:1]

In [71]:
y.head()

        mpg
0 -0.146664
1 -0.226451
2 -0.146664
3 -0.199856
4 -0.173260

In [73]:
x = np.matrix(x)
y = np.matrix(y)
theta = np.matrix(np.array([0,0]))
x.shape, theta.shape, y.shape

((398, 2), (1, 2), (398, 1))

In [75]:
def computeError(x,y,theta):
    inner = np.power(((x * theta.T) - y), 2)
    return np.sum(inner)/(2 * len(x))

In [77]:
computeError(x,y,theta)

0.02155108338399619

In [83]:
Learn_rate = 1
iters = 1000
def gradientDescent(x,y,theta,Learn_rate,iters):
    temp = np.matrix(np.zeros(theta.shape))
    parameters = int(theta.shape[1])
    cost = np.zeros(iters)
    
    for i in range(iters):
        error = (x * theta.T) - y
        
        for j in range(parameters):
            term = np.multiply(error,x[:,j])
            temp[0,j] = theta[0,j] - ((Learn_rate/len(x)) * np.sum(term))
            
            
        theta = temp
        cost[i] = computeError(x,y,theta)
        
    return theta,cost  

new_theta,cost = gradientDescent(x,y,theta,Learn_rate,iters)
print(new_theta,cost)

[[-6.20459865e-01 -1.74065117e-16]] [0.01960564 0.01793175 0.01649149 0.01525226 0.014186   0.01326856
 0.01247918 0.01179998 0.01121558 0.01071275 0.01028011 0.00990785
 0.00958755 0.00931196 0.00907483 0.00887081 0.00869526 0.00854421
 0.00841425 0.00830242 0.00820621 0.00812342 0.00805219 0.0079909
 0.00793817 0.00789279 0.00785375 0.00782016 0.00779126 0.00776639
 0.00774499 0.00772658 0.00771074 0.00769711 0.00768538 0.00767529
 0.00766661 0.00765914 0.00765271 0.00764718 0.00764242 0.00763833
 0.00763481 0.00763177 0.00762917 0.00762692 0.00762499 0.00762333
 0.0076219  0.00762067 0.00761961 0.0076187  0.00761792 0.00761724
 0.00761666 0.00761617 0.00761574 0.00761537 0.00761505 0.00761477
 0.00761454 0.00761434 0.00761416 0.00761401 0.00761388 0.00761377
 0.00761368 0.0076136  0.00761352 0.00761346 0.00761341 0.00761337
 0.00761333 0.00761329 0.00761327 0.00761324 0.00761322 0.0076132
 0.00761319 0.00761317 0.00761316 0.00761315 0.00761314 0.00761313
 0.00761313 0.00761312 0.00761312 0.00761311 0.00761311 0.00761311
 0.0076131  0.0076131  0.0076131  0.0076131  0.0076131  0.0076131
 0.0076131  0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309 0.00761309
 0.00761309 0.00761309 0.00761309 0.00761309]

In [84]:
Model_mpg = new_theta[0,0] + (new_theta[0,1]*x)

In [88]:
import math
error = [np.power((b-a),2) for (a,b) in zip(Model_mpg,y)]
error0 = np.sum(error)
error1 = math.sqrt(error0)
error = (error0/len(y))*100
print("Error% = {}".format(error))
accuracy = 100 - error
print("Accuracy% = {}".format(accuracy))

Error% = 85.61452211881007
Accuracy% = 14.385477881189928